language: python
python:
    - "2.7"
# command to install dependencies
install:
    - pip install .
# command to run tests
script:
# FIXME If these were modules, this shouldn't be necessary
    nosetests --all-modules --traverse-namespace --with-coverage --cover-inclusive --with-id -v
after_success:
    - pip install coveralls
    - coveralls
